version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0  # Ensures frontend can access backend

networks:
  app-network:
    driver: bridge
