version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0

networks:
  app-network:
    driver: bridge
