version: "3.8"

services:
  backend:
    build: ./backend
    # Remove external port exposure - only accessible through nginx
    expose:
      - "5000"
    networks:
      - app-network
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env

  frontend:
    build: ./frontend
    # Remove external port exposure - only accessible through nginx
    expose:
      - "5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0 

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
